### Test 1 - update product history
POST https://two025-estok-backend.onrender.com/api/estok/employee/create-employee
Content-Type: application/json
x-api-key: 
Authorization: Bearer token


{
  "name": "",
  "email": "",
  "gender_name": "",
  "password": "",
}

### Test 2 - getting employees
GET https://two025-estok-backend.onrender.com/api/estok/employee/get-employees
Content-Type: application/json
x-api-key: 
Authorization: Bearer token

