## Test 1 - update product history
POST https://two025-estok-backend.onrender.com/api/estok/iot/updateProductHistory
Content-Type: application/json
x-api-key: 

{
  "epc": "E200471653F06426899E010C",
  "status": "saiu"
}
