### Test 1 - Get history history
GET https://two025-estok-backend.onrender.com/api/estok/product/get-history
Content-Type: application/json
x-api-key: 

### Test 2 - Get all product status
GET https://two025-estok-backend.onrender.com/api/estok/product/get-product-status
Content-Type: application/json
x-api-key: 
